/**
 * Build owned Python runtimes with uv. Identify the GPU before installing.
 * On AMD, pin PyTorch and Triton to the ROCm source index; a version pin alone
 * also permits CUDA wheels. Other packages still resolve from PyPI.
 * Build and verify in staging before replacing the runtime. Keep weights separate.
 * Every subprocess uses the injected Runner for deadlines and test control.
 */

import { chmod, mkdir, open, readFile, readdir, rename, rm, writeFile, type FileHandle } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join } from "node:path"
import { homedir } from "node:os"
import { DEFAULT_TIMEOUT_MS, type Runner } from "./subprocess.ts"
import type { ModelSpec } from "./models.ts"
import type { StdioBackend } from "./backend/spec.ts"

/**
 * PyTorch's ROCm index. AMD's smaller multi-arch distribution needs source pins
 * for its whole SDK because its `rocm` package name conflicts with a PyPI stub.
 */
export const ROCM_INDEX = {
  name: "pytorch-rocm",
  url: "https://download.pytorch.org/whl/rocm7.2",
} as const

/**
 * Reject CUDA package names in AMD lock files before downloading runtime wheels.
 */
const FORBIDDEN_ON_AMD = /^(nvidia-|cuda-|cuda$|triton$)/

export interface Gpu {
  vendor: "amd" | "nvidia"
  /** e.g. `gfx1201`. Absent for NVIDIA, where the arch list is not the question. */
  gfx?: string
}

export interface Runtime {
  name: string
  dir: string
  python: string
  installed: boolean
  /** Only present once `meta.json` has been written, which is the last step. */
  meta?: { model: string; gfx?: string; created: string; torch?: string }
}

function dataRoot(): string {
  return process.env.ONESYSTEM_DATA_DIR ?? join(homedir(), ".local", "share", "onesystem")
}

/**
 * Runtime root. Each model directory is replaced on reinstall; keep user files
 * and weights elsewhere.
 */
export function runtimesRoot(): string {
  return join(dataRoot(), "runtimes")
}

/**
 * Persistent weights, separate from disposable runtimes. Models need separate
 * environments because their dependency pins differ.
 */
export function weightsDir(model: string): string {
  return join(dataRoot(), "weights", model)
}

export function runtimeDir(model: string): string {
  return join(runtimesRoot(), model)
}

/**
 * Check command availability without running the command.
 */
async function have(cmd: string, runner: Runner): Promise<boolean> {
  const { code } = await runner("sh", ["-c", `command -v ${cmd}`])
  return code === 0
}

/**
 * Detect the vendor with lspci and the AMD target with rocm-smi. Refuse unknown
 * hardware rather than guess a wheel index. The runner lets tests supply GPU data.
 */
export async function detectGpu(runner: Runner): Promise<Gpu> {
  const lspci = await have("lspci", runner)
    ? await runner("sh", ["-c", "lspci | grep -iE 'vga|3d|display'"])
    : null
  const vendorLine = lspci?.stdout ?? ""

  if (/NVIDIA/i.test(vendorLine)) return { vendor: "nvidia" }
  // Word boundaries prevent ATI from matching the text "Intel Corporation".
  if (!/\b(?:AMD|ATI)\b/i.test(vendorLine)) {
    throw new Error(
      "could not identify the GPU vendor from lspci; refusing to install rather than " +
        "guessing a wheel index. onesystem supports AMD (ROCm) and NVIDIA (CUDA); " +
        "anything else is refused. On AMD, make sure lspci is installed and the card is visible.",
    )
  }

  let gfx: string | undefined
  if (await have("rocm-smi", runner)) {
    const out = await runner("rocm-smi", ["--showproductname"])
    gfx = out.stdout.match(/GFX Version:\s*(gfx\w+)/i)?.[1]
  }
  if (!gfx) {
    throw new Error(
      "AMD GPU found, but its gfx target could not be read (tried rocm-smi). " +
        "Refusing to install: a wrong arch is a runtime crash, not a slow load.",
    )
  }
  return { vendor: "amd", gfx }
}

/**
 * Generate a manifest for the detected GPU. uv source pins require direct
 * dependencies, so AMD declares torch and both ROCm Triton package names.
 * NVIDIA uses PyPI's Linux CUDA wheel without an accelerator index override.
 */
export function pyprojectFor(spec: ModelSpec, gpu: Gpu): string {
  // Fetched packages use a local source path instead of a PyPI version pin.
  const local = spec.source ? `${spec.name}-src` : null
  // A fetched model contributes its own dependencies; the runtime also needs the MCP
  // SDK, because the shim that puts it behind a tool surface runs inside this
  // interpreter and nowhere else.
  const extra = spec.needsMcp ? ["mcp"] : []
  const requirement = local ? spec.requirement.replace(/==.*/, "") : spec.requirement
  const declared = [requirement, ...extra]

  // Both GPU branches need the local source for packages absent from PyPI.
  const localSource = local
    ? `\n[tool.uv.sources]\n${requirement} = { path = "${local}" }\n`
    : ""

  if (gpu.vendor !== "amd") {
    return `# Generated by \`onesystem install ${spec.name}\`. Edits will be overwritten.
[project]
name = "onesystem-runtime-${spec.name}"
version = "0.0.0"
requires-python = "${spec.requiresPython}"
# No accelerator pin: on Linux, PyPI's torch already is the CUDA build.
dependencies = [${declared.map((d) => `"${d}"`).join(", ")}]

[tool.uv]
environments = ["sys_platform == 'linux'"]
${localSource}`
  }

  return `# Generated by \`onesystem install ${spec.name}\`. Edits will be overwritten.
[project]
name = "onesystem-runtime-${spec.name}"
version = "0.0.0"
requires-python = "${spec.requiresPython}"
dependencies = [
${declared.map((d) => `  "${d}",`).join("\n")}
  # Declared so the source pin below can bind to it. See the module comment.
  "torch>=2.0.0",
  "triton-rocm>=0.0.0",
  "pytorch-triton-rocm>=0.0.0",
]

[tool.uv]
environments = ["sys_platform == 'linux'"]

[tool.uv.sources]
${local ? `${requirement} = { path = "${local}" }
` : ""}torch = { index = "${ROCM_INDEX.name}" }
triton-rocm = { index = "${ROCM_INDEX.name}" }
pytorch-triton-rocm = { index = "${ROCM_INDEX.name}" }

[[tool.uv.index]]
name = "${ROCM_INDEX.name}"
url = "${ROCM_INDEX.url}"
# Reachable only for the three names above. Without this, PyPI stays a candidate for
# torch and the CUDA wheel wins.
explicit = true
`
}

/**
 * Check AMD lock files for CUDA packages and a non-ROCm torch build before uv sync.
 */
export function assertNoAcceleratorMixups(lock: string, gpu: Gpu): void {
  if (gpu.vendor !== "amd") return

  // Read per `[[package]]` block rather than by a single regex over the file. A lock can
  // legitimately list the same name twice under different markers, and a pattern that
  // takes the first match then reports the wrong version for the one that matters.
  const entries = lock
    .split("[[package]]")
    .map((b) => ({
      name: b.match(/^\s*name = "([^"]+)"/m)?.[1],
      version: b.match(/^\s*version = "([^"]+)"/m)?.[1],
    }))
    .filter((e) => e.name !== undefined)
    .map((e) => ({ name: e.name!, version: e.version }))

  const bad = entries.map((e) => e.name).filter((n) => FORBIDDEN_ON_AMD.test(n))
  if (bad.length > 0) {
    throw new Error(
      `the resolved environment contains NVIDIA packages on an AMD GPU: ${bad.join(", ")}.\n` +
        `This means torch resolved from PyPI rather than ${ROCM_INDEX.url}.`,
    )
  }

  const torch = entries.find((e) => e.name === "torch")
  if (!torch) throw new Error("the lock has no torch entry; cannot check the accelerator build")
  // A ROCm wheel carries `+rocmX.Y` as a local version segment. That is the signal, and it
  // is the same one `torch.version.hip` reports from inside the venv.
  if (!/rocm|hip/i.test(torch.version ?? "")) {
    throw new Error(
      `torch resolved to ${torch.version ?? "an unknown version"}, which is not a ROCm build. ` +
        `A ROCm wheel's version carries a "+rocm" segment.`,
    )
  }
}

export interface InstallOptions {
  /**
   * Required runner for all subprocesses. The CLI supplies run; tests supply a script.
   */
  runner: Runner
  /** Skip the download and only resolve. Useful for checking a manifest. */
  lockOnly?: boolean
  onProgress?: (message: string) => void
  /**
   * Deadline per subprocess. Increase for slow downloads.
   */
  timeoutMs?: number
}

/**
 * Resolve, sync, and verify in staging before replacing a runtime. Write meta.json
 * only after verification; listRuntimes uses it to identify completed installs.
 */
export async function install(spec: ModelSpec, options: InstallOptions): Promise<Runtime> {
  const { runner, timeoutMs = DEFAULT_TIMEOUT_MS } = options
  if (!(await have("uv", runner))) {
    throw new Error("uv is not on PATH. Install it from https://docs.astral.sh/uv/ — it is the only dependency.")
  }
  const gpu = await detectGpu(runner)

  const dir = runtimeDir(spec.name)
  const say = options.onProgress ?? (() => {})
  say(`installing ${spec.name} for ${gpu.gfx} into ${dir}`)

  // Built in place and moved into position at the end, so a killed run never leaves a
  // directory that looks installed.
  const staging = `${dir}.partial`
  await rm(staging, { recursive: true, force: true })
  await mkdir(staging, { recursive: true })

  // Remove staging on every failure. Weights live outside staging and survive cleanup.
  try {
    let revision: string | undefined
    if (spec.source) {
      revision = await fetchModelSource(spec, join(staging, `${spec.name}-src`), say, runner, timeoutMs)
    }
    if (spec.weights) {
      // Fetched outside the staging directory, because the weights outlive this install and
      // the directory does not.
      await fetchWeights(spec, weightsDir(spec.name), say, runner, timeoutMs)
    }
    await writeFile(join(staging, "pyproject.toml"), pyprojectFor(spec, gpu))

    // Name the failed step so resolution and download errors can be distinguished.
    const lock = await runner("uv", ["lock"], { cwd: staging, timeoutMs })
    if (lock.timedOut) throw new Error(`uv lock did not finish within ${timeoutMs}ms`)
    if (lock.code !== 0) throw new Error(`uv lock failed:\n${lock.stderr.trim()}`)
    assertNoAcceleratorMixups(await readFile(join(staging, "uv.lock"), "utf8"), gpu)
    say("resolved, no NVIDIA packages")

    if (options.lockOnly) {
      // Deliberately not published. Nothing was installed, and a directory that exists
      // without a meta.json is exactly what `runtimes` reports as a half-install.
      await rm(staging, { recursive: true, force: true })
      return { name: spec.name, dir, python: pythonIn(dir), installed: false }
    }

    const sync = await runner("uv", ["sync", "--frozen"], { cwd: staging, timeoutMs })
    if (sync.timedOut) throw new Error(`uv sync did not finish within ${timeoutMs}ms`)
    if (sync.code !== 0) throw new Error(`uv sync failed:\n${sync.stderr.trim()}`)
    const check = await verify(staging, gpu, runner, timeoutMs)
    if (!check.ok) {
      // The `catch` below removes the staging directory; an environment that failed its
      // own checks is never published, and never left behind for `listRuntimes` to
      // reason about.
      throw new Error(`the installed environment failed its checks:\n  ${check.problems.join("\n  ")}`)
    }

    // Replace only after verification. The old runtime is briefly absent before rename.
    await rm(dir, { recursive: true, force: true })
    await writeFile(
      join(staging, "meta.json"),
      JSON.stringify({ model: spec.name, gfx: gpu.gfx, created: new Date().toISOString(), revision }, null, 2),
    )
    await rename(staging, dir)

    // The rename is what breaks every console script in the venv, so it is repaired here
    // rather than discovered later.
    await repairShebangs(dir, staging, pythonIn(dir))

    return { name: spec.name, dir, python: pythonIn(dir), installed: true }
  } catch (err) {
    await rm(staging, { recursive: true, force: true }).catch(() => {})
    throw err
  }
}

/**
 * Fetch package files without weights. uv caches the temporary huggingface_hub tool.
 */
async function fetchModelSource(
  spec: ModelSpec,
  into: string,
  say: (m: string) => void,
  runner: Runner,
  timeoutMs: number,
): Promise<string> {
  const { repo, allow } = spec.source!
  say(`fetching ${repo} (package only)`)
  const script = [
    "import sys, json",
    "from huggingface_hub import snapshot_download",
    `p = snapshot_download(${JSON.stringify(repo)}, local_dir=sys.argv[1], allow_patterns=${JSON.stringify(allow)})`,
    "print(json.dumps({'path': p}))",
  ].join("\n")
  const res = await runner("uv", ["run", "--quiet", "--with", "huggingface_hub", "python", "-c", script, into], {
    timeoutMs,
  })
  if (res.timedOut) throw new Error(`fetching ${repo} did not finish within ${timeoutMs}ms`)
  if (res.code !== 0) {
    throw new Error(`could not fetch ${repo}:\n${res.stderr.trim().slice(-600)}`)
  }
  return res.stdout.trim().split("\n").pop() ?? ""
}

async function fetchWeights(
  spec: ModelSpec,
  into: string,
  say: (m: string) => void,
  runner: Runner,
  timeoutMs: number,
): Promise<void> {
  if (existsSync(join(into, ".complete"))) {
    say(`weights already present in ${into}`)
    return
  }
  say(`fetching weights for ${spec.name} (${spec.weights!.repo})`)
  const script = [
    "import sys",
    "from huggingface_hub import snapshot_download",
    `snapshot_download(${JSON.stringify(spec.weights!.repo)}, local_dir=sys.argv[1])`,
  ].join("\n")
  const res = await runner("uv", ["run", "--quiet", "--with", "huggingface_hub", "python", "-c", script, into], {
    timeoutMs,
  })
  if (res.timedOut) throw new Error(`fetching weights for ${spec.name} did not finish within ${timeoutMs}ms`)
  if (res.code !== 0) throw new Error(`could not fetch weights for ${spec.name}:\n${res.stderr.trim().slice(-600)}`)
  // Mark completion last so an interrupted fetch is retried.
  await writeFile(join(into, ".complete"), new Date().toISOString())
}

export function pythonIn(dir: string): string {
  return join(dir, ".venv", "bin", "python")
}

/**
 * Repair absolute shebangs after moving the staged environment. Python itself can
 * pass verification while console scripts still point to the deleted staging path.
 * Change only shebangs naming staging; preserve other interpreters and script bodies.
 */
export async function repairShebangs(dir: string, staging: string, python: string): Promise<number> {
  const bin = join(dir, ".venv", "bin")
  let entries: string[]
  try {
    entries = await readdir(bin)
  } catch {
    return 0
  }

  let fixed = 0
  for (const name of entries) {
    const file = join(bin, name)
    // Read only a prefix when checking large binaries for a shebang.
    let handle: FileHandle | undefined
    try {
      handle = await open(file, "r")
      const head = Buffer.alloc(512)
      const { bytesRead } = await handle.read(head, 0, 512, 0)
      const first = head.subarray(0, bytesRead).toString("utf8").split("\n", 1)[0] ?? ""
      if (!first.startsWith("#!") || !first.includes(staging)) continue

      const body = await handle.readFile()
      const rest = body.toString("utf8").split("\n").slice(1).join("\n")
      await writeFile(file, `#!/usr/bin/env -S ${python.replace(/ /g, "\\ ")}\n${rest}`)
      await chmod(file, 0o755)
      fixed++
    } catch {
      // Not a readable regular file (a symlink to one, a socket). Nothing to repair.
    } finally {
      await handle?.close().catch(() => {})
    }
  }
  return fixed
}

/**
 * Check PyTorch and GPU visibility for install and doctor. A ROCm build reports a
 * HIP version and no CUDA version. Bound the import through the supplied runner.
 */
export async function verify(
  dir: string,
  gpu: Gpu,
  runner: Runner,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<{ ok: boolean; problems: string[]; torch?: string }> {
  const python = pythonIn(dir)
  if (!existsSync(python)) return { ok: false, problems: [`no interpreter at ${python}`] }

  const script = [
    "import json, torch",
    "out = {",
    "  'hip': torch.version.hip,",
    "  'cuda': torch.version.cuda,",
    "  'available': torch.cuda.is_available(),",
    "  'arch': list(torch.cuda.get_arch_list()),",
    "}",
    "print(json.dumps(out))",
  ].join("\n")

  const res = await runner(python, ["-c", script], { timeoutMs })
  if (res.timedOut) {
    // Worth its own message. `import torch` on a busy GPU can take a while, and "timed
    // out" with no hint reads like a wedged process rather than a slow import.
    return { ok: false, problems: [`importing torch did not finish within ${timeoutMs}ms`] }
  }
  if (res.code !== 0) return { ok: false, problems: [`could not import torch: ${res.stderr.trim().slice(-400)}`] }

  let info: { hip: string | null; cuda: string | null; available: boolean; arch: string[] }
  try {
    info = JSON.parse(res.stdout.trim().split("\n").pop()!)
  } catch {
    return { ok: false, problems: [`torch did not report readable state: ${res.stdout.trim().slice(-200)}`] }
  }

  const problems: string[] = []
  // The cheap discriminator: a ROCm build reports a HIP version and no CUDA version.
  // The check is vendor-specific: demanding HIP on an NVIDIA box rejects a correct
  // CUDA build, and vice versa. lspci tells us which one to ask for.
  if (gpu.vendor === "amd") {
    if (info.cuda !== null) problems.push("this is a CUDA build of torch; it cannot see an AMD GPU")
    if (info.hip === null) problems.push("torch reports no HIP version, so it is not a ROCm build")
    if (gpu.gfx && !info.arch.includes(gpu.gfx)) {
      problems.push(`torch was not built for ${gpu.gfx}; it knows ${info.arch.join(", ") || "nothing"}`)
    }
  } else {
    if (info.hip !== null) problems.push("this is a ROCm build of torch; it cannot see an NVIDIA GPU")
    if (info.cuda === null) problems.push("torch reports no CUDA version, so it is not a CUDA build")
  }
  if (!info.available) problems.push("torch.cuda.is_available() is false: no GPU visible to this interpreter")
  return { ok: problems.length === 0, problems, torch: info.hip ?? info.cuda ?? undefined }
}

export async function listRuntimes(): Promise<Runtime[]> {
  const root = runtimesRoot()
  if (!existsSync(root)) return []
  const names = await readdir(root, { withFileTypes: true })
  const out: Runtime[] = []
  for (const entry of names) {
    if (!entry.isDirectory() || entry.name.endsWith(".partial")) continue
    const dir = join(root, entry.name)
    const python = pythonIn(dir)
    const installed = existsSync(python) && existsSync(join(dir, "meta.json"))
    let meta: Runtime["meta"]
    if (installed) {
      // Read metadata only when the completion marker and interpreter exist.
      meta = JSON.parse(await readFile(join(dir, "meta.json"), "utf8"))
    }
    out.push({ name: entry.name, dir, python, installed, meta })
  }
  return out
}

export async function uninstall(name: string): Promise<boolean> {
  const dir = runtimeDir(name)
  if (!existsSync(dir)) return false
  await rm(dir, { recursive: true, force: true })
  return true
}

/**
 * Build one config block for both writing and printing. Resolve the command from
 * the installed entryPoint, then this repo's shim, then an explicit REPLACE marker.
 * Use declared tools so config generation does not start a model.
 */
export async function backendFor(spec: ModelSpec, runtime: Runtime): Promise<StdioBackend> {
  // `tools` is optional on the type but required for a config to load: `validate` rejects
  // an empty list, so a model declaring none would produce a block that cannot be used.
  // That is a gap in the model table, not something to paper over here.
  if (!spec.tools || spec.tools.length === 0) {
    throw new Error(
      `cannot write a config block for ${spec.name}: it declares no tools, and they cannot be ` +
        `discovered without loading the model. Add \`tools\` to its ModelSpec in src/models.ts.`,
    )
  }

  const command = await resolveCommand(spec, runtime)
  const env: Record<string, string> = {}
  if (spec.interpreterEnv) env[spec.interpreterEnv] = runtime.python
  if (spec.weights) env[spec.weights.envVar] = weightsDir(spec.name)

  return {
    transport: "stdio-mcp",
    command,
    ...(Object.keys(env).length > 0 ? { env } : {}),
    // Generous because laya's server is silent for ~30s importing transformers before it
    // binds stdio. See stdio-mcp.ts.
    startupTimeoutSecs: 180,
    tools: [...spec.tools],
  }
}

/** The three-step resolution described on `backendFor`. */
async function resolveCommand(spec: ModelSpec, runtime: Runtime): Promise<string[]> {
  if (spec.entryPoint) {
    const bin = join(runtime.dir, ".venv", "bin", spec.entryPoint)
    if (existsSync(bin)) return [bin]
    // Use the fallback instead of returning a nonexistent binary path.
  }
  if (spec.weights) {
    // A model that ships a library: the runtime's interpreter runs our shim beside it.
    const shim = new URL(`./shims/${spec.name}-mcp.py`, import.meta.url).pathname
    if (existsSync(shim)) return [runtime.python, shim]
  }
  return [`REPLACE: path to the ${spec.name} MCP server binary on your machine`]
}

/** True when `backendFor` produced something a person still has to fill in. */
export function needsManualCommand(backend: StdioBackend): boolean {
  return backend.command.some((arg) => arg.startsWith("REPLACE:"))
}

/**
 * Render the same backend object for --no-config or a failed config write.
 */
export function renderBackend(name: string, backend: StdioBackend): string {
  const lines = JSON.stringify(backend, null, 2).split("\n")
  const inner = lines
    .slice(1, -1)
    .map((line) => `  ${line}`)
    .join("\n")
  return `  "${name}": {\n${inner}\n  }`
}

/** Print a backend built by `backendFor`. */
export function configHint(spec: ModelSpec, runtime: Runtime, backend?: StdioBackend): string {
  // `backend` is passed by `onesystem install` so the printed form is the resolved one,
  // entry point and all. The fallback re-derives the marker form for the rare caller that
  // only has a spec and a runtime.
  if (backend) return renderBackend(spec.name, backend)
  const marker: StdioBackend = {
    transport: "stdio-mcp",
    command: spec.weights
      ? [runtime.python, `/path/to/onesystem/src/shims/${spec.name}-mcp.py`]
      : [`REPLACE: path to the ${spec.name} MCP server binary on your machine`],
    tools: [...(spec.tools ?? [])],
  }
  return renderBackend(spec.name, marker)
}
